<?php

/**
 * @file
 * Provides tools for implementing and custom block.
 */

/**
 * Implementation of hook theme.
 */

/**
 * Implementation of hook_theme.
 *
 * @param [type] $existing
 * @param [type] $type
 * @param [type] $theme
 * @param [type] $path
 *
 * @return void
 */
function user_profile_data_theme($existing, $type, $theme, $path) {
  return [
    'custom_user_profile_block_template' => [
      'variables' => ['output' => NULL],
      'template' => 'custom-user-profile-block-template',
    ],
  ];
}
