# Schema for the configuration files of the my_bo module.
action.configuration.add_premium_content:
  type: action_configuration_default
  label: 'Make Content Premium'

action.configuration.remove_premium_content:
  type: action_configuration_default
  label: 'Make Content Non-Premium'
