eventchat.settings:
  type: config_object
  label: 'EventChat Config'
  mapping:
    eventchat_sid: 
      type: string
    eventchat_iflychat_app_id:
      type: string
    eventchat_iflychat_api_key:
      type: string