<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function nlr_custom_print_theme($existing, $type, $theme, $path) {

  return [
    'print_email' => [
      'variables' => [
        'share' => NULL,
        'nid' => NULL,
        'base_url' => NULL,
        'uid' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_mail().
 */
function nlr_custom_print_mail($key, &$message, $params) {

  switch ($key) {
    case 'node_email':
      $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
      $message['from'] = $params['email'];
      $message['sender_name'] = $params['name'];
      $message['subject'] = $params['subject'];
      $message['body'][0] = $params['message'] . '<br /><a href="' . $params['path'] . '">' . $params['title'] . '</a>';
      break;
  }
}
